name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: patric-dosch-vi/solr-action@v1
        id: hello
        with:
          version: 8.11.1
          core name: corename
          config path: test/resources/solr/conf

      - run: echo "The command was ${{ steps.hello.outputs.outttt }}"

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: npm ci
        working-directory: test

      - run: node index.js
        working-directory: test
